### PR TITLE
Use single linux binary

### PR DESCRIPTION
**Pull request by ljbade**
See https://github.com/mapbox/mason/issues/47

### CODE REVIEW

**Comment by ljbade** [comment]
I changed the linux binary to just be `linux-arch`

@kkaefer and @springmeyer can you review?

**Comment by springmeyer** [comment]
Looks good to me. As discussed on chat this change means:

  - Travis will be able to build binaries that work on Ubuntu 12.04 and greater. Therefore Ubuntu 14.04 users to start getting binaries right away. It also means that other modern distros will start working too out of the box like RHEL 7 (as long as their libc is as recent as Ubuntu 12.04, which is a very good bet).
  - When Travis upgrades to Ubuntu 14.04 this change will have the impact that we'll drop Ubuntu 12.04 support. All binaries that might get rebuilt would then be broken on Ubuntu 12.04. This is because the libc is newer on 14.04 and linux offers only forward compatibility and not back compatibility in terms of how symbol versioning works in libc.

One recommendation: I'd like Mason to keep reporting `MASON_PLATFORM_DISTRIBUTION` - seems handy to make that available even if we don't use it to version `MASON_PLATFORM_VERSION`.

**Comment by ljbade** [comment]
Oh yeah Ill add that back then.

**Comment by springmeyer** [comment]
:+1:

**Pull request merged**
