### PR TITLE
update to c++11 for tippecanoe

### PR DESCRIPTION
**Pull request by camilleanne**
cc @springmeyer

### CODE REVIEW

**Comment by springmeyer** [comment]
@camilleanne - for your downstream need can the latest tagged release of tippecanoe be used? (1.15.1) /cc @ericfischer 

Asking because it is ideal to use 1.15.1 if that is sufficient. If not - if you need an unreleased version - then the convention now after https://github.com/mapbox/mason/issues/213 is to use the gitsha for versioning instead of `latest`.

**Comment by springmeyer** [comment]
https://github.com/mapbox/mason/blob/master/scripts/luabind/e414c57bcb687bb3091b7c55bbff6947f052e46b/script.sh is an example of a C++ library that uses an unreleased gitsha, and is therefor named that way.

**Comment by camilleanne** [comment]
@springmeyer yes, `1.15.1` will be fine for our needs -- should I expand this PR to pin to that version?

**Comment by springmeyer** [comment]
> @springmeyer yes, 1.15.1 will be fine for our needs -- should I expand this PR to pin to that version?

Yes. I would recommend creating:

  - using this branch
  - create a new package at `scripts/tippecanoe/1.15.1/`
  - copying the script.sh and .travis.yml over from the `latest` folder
  - edit appropriately
  - commit, and trigger a new build for the new version
  - then we'll merge this (okay to leave the latest, we can cull later).

**Comment by ericfischer** [comment]
Thanks for updating the mason scripts @camilleanne! I'll be glad to have this example to copy next time I tag a new release.

**Comment by camilleanne** [comment]
@springmeyer ok, done and done.

**Comment by springmeyer** [comment]
@camilleanne okay, I'm testing and fixing up a few things locally:

 - libprotobuf is no longer a dependency
 - upgrading the sqlite3 version used
 - using the release tarball: https://github.com/mapbox/tippecanoe/archive/${MASON_VERSION}.tar.gz

**Pull request merged**
