### PR TITLE
[WIP] RocksDB 5.4.6

### PR DESCRIPTION
**Pull request by lukasmartinelli**
I need a newer version of RocksDB. Will follow up later.

### CODE REVIEW

**Comment by springmeyer** [comment]
👍 Take a look at https://github.com/mapbox/mason/compare/rocksdb-update. @aarthykc @KaiBot3000 and I packaged 5.3.6 and found the build had changed enough it required some tweaks. We did not end up landing the 5.3.6 package, so what I'd recommend is you:

 - [ ] Copy the `script.sh` into your branch from the `rocksdb-update` branch (modify the version and hash as needed)
 - [ ] Ensure it builds locally for you: `./mason build rocksdb <version>`
 - [ ]  Push your branch and trigger builds: `./mason trigger rocksdb <version>` (docs for getting set up to trigger builds at https://github.com/mapbox/mason/#trigger).
 - [ ] Ask for final review here.

**Comment by lukasmartinelli** [comment]
The instructions was exactly what I was looking for. Thanks a lot Dane!

**Comment by lukasmartinelli** [comment]
Publish worked: https://travis-ci.org/mapbox/mason/builds/262724753
Also built it locally and linked it in another project to test.

Ready for review.

**Comment by springmeyer** [comment]
Thanks. Your PR looks great. Seeing one issue I need to debug myself: the build is not portable by default since it includes the `-march=native` flag. Will post back when I've had a chance to investigate.

**Comment by springmeyer** [comment]
Okay, this all checks out. I poked at whether the sse4.2 optimizations, enabled automatically in the build, will work on the AWS machines we target. I think they should per https://github.com/mapbox/mason/pull/462, which I've merged into this branch. Now I'll merge this PR and we're done. Because https://github.com/mapbox/osm-tag-history/issues/18 is using the mason `cmake` client, the package should already be ready and you don't need to do anything else to use it (e.g. you don't need to update mason). But let me know if you run into any problems.

**Pull request merged**
