### PR TITLE
Add Shapeinfo library

### PR DESCRIPTION
**Pull request by oxidase**
Added " The Shapefile C Library provides the ability to write simple C programs for reading, writing and updating (to a limited extent) ESRI Shapefiles, and the associated attribute file (.dbf)."
http://shapelib.maptools.org/

### CODE REVIEW

**Comment by springmeyer** [comment]
Thanks @oxidase. The `script.sh` looks good. I will test it shortly to make sure it builds okay on OS X. Can you please replace the `.travis.yml` with https://github.com/mapbox/mason/blob/master/scripts/freetype/2.7.1/.travis.yml - that builds for just osx/linux in a way consistent with most recent packages (I presume we don't need shplib builds for OSRM for any platforms besides osx/linux).

**Comment by springmeyer** [comment]
@oxidase I rebased to fix the conflict and added optimization flags to the build. We add `CFLAGS` environment per platform in mason's default environment, but this does not (yet) include `-O3`. It looks like this was overriding the `-O2` in the makefile, so I've fixed it now to pass `-O3`. I'll plan to merge this soon. Currently aws s3 is down which prevents proper testing. Will wait on that, then merge.

**Comment by oxidase** [comment]
@springmeyer just added a patch for makefile: in the original makefile environments variables are ignored. i also removed exporting CFLAGS.

**Comment by springmeyer** [comment]
Great, merging now. Thanks for getting this going.

**Pull request merged**
