### PR TITLE
Add Tippecanoe 1.21.0

### PR DESCRIPTION
**Pull request by ericfischer**

### CODE REVIEW

**Comment by mapsam** [comment]
triggered builds successfully:

```
https://mason-binaries.s3.amazonaws.com/osx-x86_64/tippecanoe/1.21.0.tar.gz
https://mason-binaries.s3.amazonaws.com/linux-x86_64/tippecanoe/1.21.0.tar.gz
```

Seeing this error on Travis: `The MASON_PKGCONFIG_FILE variable not found in script.sh. Please either provide this variable or override the mason_cflags function hook` and not really sure how to diagnose.

cc @flippmoke

**Comment by mapsam** [comment]
Maybe we just need to add `MASON_PKGCONFIG_FILE=lib/tippecanoe.pc` to the scripts.sh file?

**Comment by ericfischer** [comment]
Looks like that's what the other scripts do…

**Comment by ericfischer** [comment]
But those are all for libraries… Does it make sense to have `MASON_PKGCONFIG_FILE` when Tippecanoe is just a program, not a library?

**Comment by ericfischer** [comment]
The confusing part is that `tippecanoe/1.21.0/script.sh` *does* override the `mason_cflags` function.

**Comment by ericfischer** [comment]
Looks like the build error is actually happening in `/Users/travis/build/mapbox/mason/mason_packages/osx-x86_64/android-ndk/arm-9-r13b`, not in the Tippecanoe script?

**Comment by mapsam** [comment]
Ah, good eye @ericfischer you're right. Getting a 👍 from @springmeyer or @flippmoke to merge this would be great.

**Comment by springmeyer** [comment]
> Ah, good eye @ericfischer you're right. Getting a 👍 from @springmeyer or @flippmoke to merge this would be great.

👍  all good to merge. The build errors look like spurious network issues that had other consequences unrelated to this PR. Ticketed at #456

**Comment by mapsam** [comment]
Thanks @springmeyer!

**Pull request merged**
