### PR TITLE
add libosmium @ 14d92d6

### PR DESCRIPTION
**Pull request by camilleanne**
cc @springmeyer 

* [ ] point timtam to this branch
* [x] trigger build
* [ ] test build

### CODE REVIEW

**Comment by springmeyer** [comment]
Looks good. Are you set up to trigger builds (in order to publish). If so feel free to trigger a build then you can:

 - update your mason version to point at this branch
 - test your build
 - if it works then merge this!

**Comment by springmeyer** [comment]
@camilleanne - ran it locally and found a few things needing updated: done in d95dfad. Back to you to try triggering a build to publish. Follow the notes at https://github.com/mapbox/mason#trigger

**Comment by camilleanne** [comment]
I might update this pr to include this commit: https://github.com/osmcode/libosmium/commit/67bc8b12cf9697647cd6d8c0328f3f1f6ab6ca18 "Speeds up writing of PBF files by 10% and more."

**Comment by springmeyer** [comment]
closing, libosmium 2.8.0 is out (thanks @camilleanne and @joto for the work behind this) - I'll add a package for it as part of #223

**Pull request closed without merging**
