### PR TITLE
[toolchain] Fix android build when HOST == TARGET

### PR DESCRIPTION
**Pull request by tmpsantos**
Pass the `sysroot` to the compiler and linker otherwise they will look in to the host search path.

### CODE REVIEW

**Comment by tmpsantos** [comment]
:eyes: @bleege

**Comment by bleege** [comment]
I tried this out locally in the `release-android-v4.1.0` branch and it still failed when building MIPS.  My process was:

1. Update to latest on `release-android-v4.1.0` ( https://github.com/mapbox/mapbox-gl-native/commit/b0de21ed1de5ff166e10d9282224aa92413cb25a )
1. Update local copy of `.mason/mason.sh` with b73fc3ed4aaaf5fb24c5ff7d34c33c7c873e4899
1. Run `make clean`
1. Run `make apackage`

Log message:

```
MASON_PLATFORM="android" MASON_ANDROID_ABI="mips" CXX="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-clang++" CC="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-clang" LD="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-ld" LINK="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-clang++" AR="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-ar" RANLIB="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-ranlib" STRIP="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-strip" LDFLAGS="--sysroot=/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/sysroot -target mipsel-none-linux-android -no-canonical-prefixes -Wl,--warn-shared-textrel -Wl,--fatal-warnings ${LDFLAGS:-}" CFLAGS="--sysroot=/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/sysroot -target mipsel-none-linux-android -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-integrated-as -fomit-frame-pointer -fstrict-aliasing -Wno-invalid-command-line-argument -Wno-unused-command-line-argument ${CFLAGS:-}" CXXFLAGS="--sysroot=/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/sysroot --sysroot=/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/sysroot -target mipsel-none-linux-android -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-integrated-as -fomit-frame-pointer -fstrict-aliasing -Wno-invalid-command-line-argument -Wno-unused-command-line-argument ${CXXFLAGS:-}" CPPFLAGS="-D__ANDROID__ ${CPPFLAGS:-}" JNIDIR="mips" deps/run_gyp --depth=. -Goutput_dir=. -f make-android -I build/android-mips/config.gypi --generator-output=build/android-mips platform/android/platform.gyp
MASON_PLATFORM="android" MASON_ANDROID_ABI="mips" CXX="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-clang++" CC="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-clang" LD="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-ld" LINK="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-clang++" AR="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-ar" RANLIB="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-ranlib" STRIP="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-strip" LDFLAGS="--sysroot=/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/sysroot -target mipsel-none-linux-android -no-canonical-prefixes -Wl,--warn-shared-textrel -Wl,--fatal-warnings ${LDFLAGS:-}" CFLAGS="--sysroot=/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/sysroot -target mipsel-none-linux-android -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-integrated-as -fomit-frame-pointer -fstrict-aliasing -Wno-invalid-command-line-argument -Wno-unused-command-line-argument ${CFLAGS:-}" CXXFLAGS="--sysroot=/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/sysroot --sysroot=/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/sysroot -target mipsel-none-linux-android -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-integrated-as -fomit-frame-pointer -fstrict-aliasing -Wno-invalid-command-line-argument -Wno-unused-command-line-argument ${CXXFLAGS:-}" CPPFLAGS="-D__ANDROID__ ${CPPFLAGS:-}" JNIDIR="mips" /Applications/Xcode.app/Contents/Developer/usr/bin/make -j4 -C build/android-mips all
  ACTION platform_android_platform_gyp_core_target_Build_Version_Header Debug/obj/gen/include/mbgl/util/version.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_0 Debug/obj/gen/include/mbgl/shader/circle.fragment.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_1 Debug/obj/gen/include/mbgl/shader/circle.vertex.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_2 Debug/obj/gen/include/mbgl/shader/collisionbox.fragment.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_3 Debug/obj/gen/include/mbgl/shader/collisionbox.vertex.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_4 Debug/obj/gen/include/mbgl/shader/debug.fragment.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_5 Debug/obj/gen/include/mbgl/shader/debug.vertex.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_6 Debug/obj/gen/include/mbgl/shader/fill.fragment.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_7 Debug/obj/gen/include/mbgl/shader/fill.vertex.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_8 Debug/obj/gen/include/mbgl/shader/icon.fragment.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_9 Debug/obj/gen/include/mbgl/shader/icon.vertex.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_10 Debug/obj/gen/include/mbgl/shader/line.fragment.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_11 Debug/obj/gen/include/mbgl/shader/line.vertex.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_12 Debug/obj/gen/include/mbgl/shader/linepattern.fragment.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_13 Debug/obj/gen/include/mbgl/shader/linepattern.vertex.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_14 Debug/obj/gen/include/mbgl/shader/linesdfpattern.fragment.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_15 Debug/obj/gen/include/mbgl/shader/linesdfpattern.vertex.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_16 Debug/obj/gen/include/mbgl/shader/outline.fragment.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_17 Debug/obj/gen/include/mbgl/shader/outline.vertex.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_18 Debug/obj/gen/include/mbgl/shader/outlinepattern.fragment.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_19 Debug/obj/gen/include/mbgl/shader/outlinepattern.vertex.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_20 Debug/obj/gen/include/mbgl/shader/pattern.fragment.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_21 Debug/obj/gen/include/mbgl/shader/pattern.vertex.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_22 Debug/obj/gen/include/mbgl/shader/raster.fragment.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_23 Debug/obj/gen/include/mbgl/shader/raster.vertex.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_24 Debug/obj/gen/include/mbgl/shader/sdf.fragment.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_25 Debug/obj/gen/include/mbgl/shader/sdf.vertex.hpp
  RULE platform_android_platform_gyp_core_target_Build_Shaders_26 Debug/obj/gen/include/mbgl/shader/util.vertex.hpp
  CXX(target) Debug/obj.target/example-custom-layer-lib/platform/android/src/example_custom_layer.o
make[1]: Circular all <- all dependency dropped.
  COPY Debug/ca-bundle.crt
  TOUCH Debug/obj.target/platform/android/copy_certificate_bundle.stamp
  CXX(target) Debug/obj.target/core/src/clipper/clipper.o
  CXX(target) Debug/obj.target/core/src/csscolorparser/csscolorparser.o
  CXX(target) Debug/obj.target/core/src/mbgl/algorithm/generate_clip_ids.o
  CXX(target) Debug/obj.target/core/src/mbgl/algorithm/update_renderables.o
  CXX(target) Debug/obj.target/core/src/mbgl/annotation/annotation_manager.o
  CXX(target) Debug/obj.target/core/src/mbgl/annotation/annotation_tile.o
  CXX(target) Debug/obj.target/core/src/mbgl/annotation/point_annotation_impl.o
  CXX(target) Debug/obj.target/core/src/mbgl/annotation/shape_annotation_impl.o
  CXX(target) Debug/obj.target/core/src/mbgl/geometry/circle_buffer.o
  CXX(target) Debug/obj.target/core/src/mbgl/geometry/collision_box_buffer.o
  CXX(target) Debug/obj.target/core/src/mbgl/geometry/debug_font_buffer.o
  CXX(target) Debug/obj.target/core/src/mbgl/geometry/elements_buffer.o
  CXX(target) Debug/obj.target/core/src/mbgl/geometry/feature_index.o
  CXX(target) Debug/obj.target/core/src/mbgl/geometry/fill_buffer.o
  CXX(target) Debug/obj.target/core/src/mbgl/geometry/glyph_atlas.o
  CXX(target) Debug/obj.target/core/src/mbgl/geometry/icon_buffer.o
  CXX(target) Debug/obj.target/core/src/mbgl/geometry/line_atlas.o
  CXX(target) Debug/obj.target/core/src/mbgl/geometry/line_buffer.o
  CXX(target) Debug/obj.target/core/src/mbgl/geometry/static_vertex_buffer.o
  CXX(target) Debug/obj.target/core/src/mbgl/geometry/text_buffer.o
  CXX(target) Debug/obj.target/core/src/mbgl/geometry/vao.o
  CXX(target) Debug/obj.target/core/src/mbgl/gl/debugging.o
  CXX(target) Debug/obj.target/core/src/mbgl/gl/gl.o
  CXX(target) Debug/obj.target/core/src/mbgl/gl/gl_config.o
/var/folders/l_/f8qygkjj6lb9s_d8yrv30crc0000gn/T/annotation_manager-0c759c.s: Assembler messages:
/var/folders/l_/f8qygkjj6lb9s_d8yrv30crc0000gn/T/annotation_manager-0c759c.s:166400: Warning: no .cprestore pseudo-op used in PIC code
/var/folders/l_/f8qygkjj6lb9s_d8yrv30crc0000gn/T/annotation_manager-0c759c.s:166400: Warning: macro instruction expanded into multiple instructions
/var/folders/l_/f8qygkjj6lb9s_d8yrv30crc0000gn/T/annotation_manager-0c759c.s:220949: Warning: no .cprestore pseudo-op used in PIC code
/var/folders/l_/f8qygkjj6lb9s_d8yrv30crc0000gn/T/annotation_manager-0c759c.s:220949: Warning: macro instruction expanded into multiple instructions
  CXX(target) Debug/obj.target/core/src/mbgl/gl/gl_object_store.o
  CXX(target) Debug/obj.target/core/src/mbgl/gl/texture_pool.o
  CXX(target) Debug/obj.target/core/src/mbgl/layer/background_layer.o
clang36++: error: unable to execute command: Segmentation fault: 11
clang36++: error: assembler command failed due to signal (use -v to see invocation)
clang version 3.6 
Target: mipsel-none-linux-android
Thread model: posix
clang36++: note: diagnostic msg: PLEASE submit a bug report to http://source.android.com/source/report-bugs.html and include the crash backtrace, preprocessed source, and associated run script.
  CXX(target) Debug/obj.target/core/src/mbgl/layer/circle_layer.o
clang36++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang36++: note: diagnostic msg: /var/folders/l_/f8qygkjj6lb9s_d8yrv30crc0000gn/T/annotation_manager-20bcc6.cpp
clang36++: note: diagnostic msg: /var/folders/l_/f8qygkjj6lb9s_d8yrv30crc0000gn/T/annotation_manager-20bcc6.sh
clang36++: note: diagnostic msg: 

********************
make[1]: *** [Debug/obj.target/core/src/mbgl/annotation/annotation_manager.o] Error 254
make[1]: *** Waiting for unfinished jobs....
/var/folders/l_/f8qygkjj6lb9s_d8yrv30crc0000gn/T/feature_index-3a35be.s: Assembler messages:
/var/folders/l_/f8qygkjj6lb9s_d8yrv30crc0000gn/T/feature_index-3a35be.s:20311: Warning: no .cprestore pseudo-op used in PIC code
/var/folders/l_/f8qygkjj6lb9s_d8yrv30crc0000gn/T/feature_index-3a35be.s:20311: Warning: macro instruction expanded into multiple instructions
/var/folders/l_/f8qygkjj6lb9s_d8yrv30crc0000gn/T/feature_index-3a35be.s:23184: Warning: no .cprestore pseudo-op used in PIC code
/var/folders/l_/f8qygkjj6lb9s_d8yrv30crc0000gn/T/feature_index-3a35be.s:23184: Warning: macro instruction expanded into multiple instructions
clang36++: error: unable to execute command: Segmentation fault: 11
clang36++: error: assembler command failed due to signal (use -v to see invocation)
clang version 3.6 
Target: mipsel-none-linux-android
Thread model: posix
clang36++: note: diagnostic msg: PLEASE submit a bug report to http://source.android.com/source/report-bugs.html and include the crash backtrace, preprocessed source, and associated run script.
clang36++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang36++: note: diagnostic msg: /var/folders/l_/f8qygkjj6lb9s_d8yrv30crc0000gn/T/feature_index-19f8ec.cpp
clang36++: note: diagnostic msg: /var/folders/l_/f8qygkjj6lb9s_d8yrv30crc0000gn/T/feature_index-19f8ec.sh
clang36++: note: diagnostic msg: 

********************
make[1]: *** [Debug/obj.target/core/src/mbgl/geometry/feature_index.o] Error 254
make: *** [android-lib-mips] Error 2
```

**Comment by bleege** [comment]
@tmpsantos has clarified that the above crash is to be expected as `BUILDTYPE=Release` environment variable still needs to be set.  I'll retry using that now.

**Comment by bleege** [comment]
Retry with `BUILDTYPE=Release` worked as expected!  Thanks @tmpsantos!

**Pull request merged**
