### PR TITLE
geojson 0.4.1

### PR DESCRIPTION
**Pull request by ivovandongen**
Small update to geojson to include https://github.com/mapbox/geojson-cpp/issues/31

### CODE REVIEW

**Comment by springmeyer** [comment]
Please hold on this. It looks like this package is intended to be built using the CXX11 ABI but I can tell that it is not actually ending up working. @ivovandongen I realize you are just here after releasing a new geojson-cpp release that needs packaged. I'm happy to fix this up so that it actually builds a CXX11 ABI version per what @tmpsantos and I learned over at https://github.com/mapbox/mason/pull/268#issuecomment-272380280.

**Comment by springmeyer** [comment]
Also more context: my understanding is that because we previously did not know how to built CXX11 ABI packages in mbgl we are using geojson-cpp as a header only library. So I'll make some changes to this PR that fixes to build to publish a working CXX11ABI package. Then we could revisit using geojson-cpp as a precompiled library in mbgl, if @mapbox/gl desires. We should have both options I think.

**Comment by springmeyer** [comment]
The above commits:

  - Fix the cxx11abi package to actually build against that ABI
  - Renamed the package with the `-cxxabi` modifier (currently the default is ABI 0 and packages with ABI 1 are named with `-cxxabi` until a future breaking mason version that might switch that default)
  - Created a non cxxabi version
  - Now compiling with clang++ like all other packages (I presume the G++ attempt there was in the hope that would enable the cxxabi. But in fact it is controlled by the libstdc++ headers and not the compiler)

I noticed one other issue. This package is depending on https://github.com/mapbox/geojson-cpp/blob/b7470e2049b2866e516134abe201d88ab2a69893/Makefile#L4-L6 for the dependency versions. These are currently the same as mbgl https://github.com/mapbox/mapbox-gl-native/blob/master/CMakeLists.txt#L41-L54 but could spell trouble if they drift (/cc @kkaefer). So I think a better approach would be to let the mason script control the versions rather that the build of geojson-cpp. This could require build modifications so those can be overriden. I can take a look at this next week.

**Comment by springmeyer** [comment]
Also noticed that there is not a tag yet for 0.4.1 at https://github.com/mapbox/geojson-cpp/releases. @ivovandongen let me know if you plan to do that?

**Comment by kkaefer** [comment]
> I noticed one other issue. This package is depending on https://github.com/mapbox/geojson-cpp/blob/b7470e2049b2866e516134abe201d88ab2a69893/Makefile#L4-L6 for the dependency versions. These are currently the same as mbgl https://github.com/mapbox/mapbox-gl-native/blob/master/CMakeLists.txt#L41-L54 but could spell trouble if they drift (/cc @kkaefer)

To circumvent this issue, we're using this library as [`HEADER_ONLY`](https://github.com/mapbox/mapbox-gl-native/blob/74ff4354623a644eb3c293ec818cebbf9c45077c/CMakeLists.txt#L52) and [compile it in the project](https://github.com/mapbox/mapbox-gl-native/blob/74ff4354623a644eb3c293ec818cebbf9c45077c/src/mbgl/util/geojson.cpp) so that it uses the same dependency headers.

**Comment by ivovandongen** [comment]
@springmeyer Thanks for fixing this up. I've added the tag here: https://github.com/mapbox/geojson-cpp/releases/tag/v0.4.1

**Comment by springmeyer** [comment]
Thanks @ivovandongen for the tag.

Thanks @kkaefer for the confirmation that mbgl will not be impacted by drifting versions currently. 

This that the cxx11abi package built as a library (and included in this PR) is not needed by mbgl. However I think we should keep this package going since it may be needed in the future by mbgl or another application. To avoid getting in trouble with drift, in the future mason should offer ways to assert that dependency versions are not in conflict - refs #403

**Pull request merged**
