### PR TITLE
libboost libprogram_options 1.62.0 cxx11abi

### PR DESCRIPTION
**Pull request by tmpsantos**
Fixes build on recent Linux distros.

### CODE REVIEW

**Comment by springmeyer** [comment]
Is this still relevant @tmpsantos?

**Comment by tmpsantos** [comment]
> Is this still relevant @tmpsantos?

Yes, mapbox-gl-native's offline cache generator is br0ken on Ubuntu 15.04+ because of this.

**Comment by tmpsantos** [comment]
I need to rewrite the Travis file, I forgot about this PR and it aged a bit.

**Comment by springmeyer** [comment]
This package is now correctly linked to the cxxabi. This can be confirmed by greping for `cxx1112basic_string` in the output of `nm mason_packages/linux-x86_64/boost_libprogram_options/1.62.0-cxx11abi/lib/libboost_program_options.a` which will show symbols like:

```
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_
```

The workaround was:

```
sudo perl -i -p -e "s/# define _GLIBCXX_USE_DUAL_ABI 0/# define _GLIBCXX_USE_DUAL_ABI 1/g;" /usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h
```

Details at https://github.com/mapbox/mason/issues/157#issuecomment-272378928

**Pull request merged**
