### PR TITLE
KCov Installation

### PR DESCRIPTION
**Pull request by ingalls**
Install the latest tagged version of KCov

Closes: https://github.com/mapbox/mason/issues/570

### CODE REVIEW

**Comment by ingalls** [comment]
Triggered Build: https://travis-ci.org/mapbox/mason/builds/353295846?utm_source=github_status&utm_medium=notification

**Comment by springmeyer** [comment]
Thanks for getting this started @ingalls. I tried to build locally on OS X to help out here and I'm hitting:

```
/Users/dane/projects/mason/mason_packages/.build/kcov-34/src/engines/lldb-engine.cc:163:32: error: ordered comparison between pointer and zero ('char *' and 'int')
                if (getcwd(buf, sizeof(buf)) < 0) {
                    ~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
1 error generated.
```

looks like a bug in kcov, perhaps fixed in master.

**Comment by springmeyer** [comment]
yep, latest kcov at https://github.com/SimonKagstrom/kcov/commit/894e98b73ef3b5e1626f66450cdcb623e368dec6 works on OS X without patching, so I've pushed a new package for that one.

**Comment by springmeyer** [comment]
Close, working except on OS X: https://travis-ci.org/mapbox/mason/builds/354103852

**Comment by ingalls** [comment]
@springmeyer thanks for taking on the OSX side of this, I no longer have an OSX instance to test against.

**Comment by springmeyer** [comment]
I'm stumped on the zlib error on travis/OSX:

```
-- Checking for module 'zlib'
--   No package 'zlib' found
CMake Error at /Users/travis/build/mapbox/mason/mason_packages/osx-x86_64/cmake/3.8.2/share/cmake-3.8/Modules/FindPkgConfig.cmake:416 (message):
  A required package was not found
Call Stack (most recent call first):
  /Users/travis/build/mapbox/mason/mason_packages/osx-x86_64/cmake/3.8.2/share/cmake-3.8/Modules/FindPkgConfig.cmake:589 (_pkg_check_modules_internal)
  src/CMakeLists.txt:13 (pkg_check_modules)
-- Configuring incomplete, errors occurred!
See also "/Users/travis/build/mapbox/mason/mason_packages/.build/SimonKagstrom-kcov-894e98b/build/CMakeFiles/CMakeOutput.log".
```

It does not happen for me locally. So, I've taken a shortcut (not best practice) and published OS X binaries from my local machine so that this can be merged. I'm going to hope that when we port to circleci in the future this will magically be solved (if we need to rebuild again):  https://github.com/mapbox/mason/issues/536

**Pull request merged**
